# Copyright 2026 Roman Kuzmitskii (@damex)
# SPDX-License-Identifier: MIT

manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      remote: nrfconnect
      revision: v3.1.1
      path: nrf

    - name: nrfxlib
      remote: nrfconnect
      repo-path: sdk-nrfxlib
      revision: v3.1.1
      path: nrfxlib

    - name: mbedtls
      remote: nrfconnect
      repo-path: sdk-mbedtls
      revision: ncs-v3.1.1
      path: modules/crypto/mbedtls

    - name: oberon-psa-crypto
      remote: nrfconnect
      repo-path: sdk-oberon-psa-crypto
      revision: ncs-v3.1.1
      path: modules/crypto/oberon-psa-crypto
